<?php

namespace App\Console\Commands;

use App\Models\Article;
use App\Models\Category;
use App\Models\Redirect;
use Illuminate\Console\Command;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;
use Throwable;

/**
 * Loads a CSV of old-CMS URLs into `redirects`.
 *
 * `RedirectResolver` is the reader; this is the only writer, because the
 * shape of this job is a mapping file with thousands of rows exported from the
 * system being replaced, not a form somebody fills in one URL at a time.
 *
 * Three things it does that matter more than the parsing:
 *
 * **It normalises `from` on the way in.** The resolver matches with and
 * without a leading slash so a hand-inserted row still works, but a table
 * where the same path is stored three ways has a `unique` index that is not
 * doing its job. One stored form: no leading or trailing slash.
 *
 * **It refuses a row that points at itself.** The resolver guards that hop at
 * request time as well, because a row can arrive any number of ways — but a
 * loop caught at import is one somebody can still fix in the file.
 *
 * **`--dry-run` reports on the file without writing.** A migration mapping is
 * usually generated by a script against the old CMS, and finding out it is
 * malformed after 4,000 rows are in the table is worse than finding out now.
 *
 * And it names the rules that will never fire — see `shadowed()`, which is
 * the check worth having here.
 */
class ImportRedirects extends Command
{
    protected $signature = 'redirects:import
        {file : CSV with a from,to[,status] header row}
        {--dry-run : Report what would be written, change nothing}';

    protected $description = 'Import old-CMS URL redirects from a CSV file';

    /** Matches `RedirectResolver::ALLOWED` — anything else is read as a typo. */
    private const ALLOWED = [301, 302, 307, 308];

    public function handle(): int
    {
        $path = $this->argument('file');

        if (! is_readable($path)) {
            $this->components->error("Cannot read {$path}.");

            return self::FAILURE;
        }

        $handle = fopen($path, 'r');
        $header = fgetcsv($handle);

        if ($header === false) {
            fclose($handle);
            $this->components->error('The file is empty.');

            return self::FAILURE;
        }

        $columns = array_flip(array_map(
            fn ($h): string => strtolower(trim((string) $h, " \t\n\r\0\x0B\xEF\xBB\xBF")),
            $header,
        ));

        foreach (['from', 'to'] as $required) {
            if (! isset($columns[$required])) {
                fclose($handle);
                $this->components->error("The header row needs a `{$required}` column.");

                return self::FAILURE;
            }
        }

        $rows = [];
        $skipped = [];
        $line = 1;

        while (($record = fgetcsv($handle)) !== false) {
            $line++;

            if ($record === [null] || $record === []) {
                continue;                       // fgetcsv's blank-line shape
            }

            $from = $this->normalise($record[$columns['from']] ?? '');
            $to = trim((string) ($record[$columns['to']] ?? ''));

            $rawStatus = isset($columns['status'])
                ? trim((string) ($record[$columns['status']] ?? ''))
                : '';
            $status = $rawStatus === '' ? 301 : (int) $rawStatus;

            if ($from === '' || $to === '') {
                $skipped[] = "line {$line}: from or to is blank";

                continue;
            }

            if ($from === $this->normalise($to)) {
                $skipped[] = "line {$line}: `{$from}` points at itself";

                continue;
            }

            if (! in_array($status, self::ALLOWED, true)) {
                $skipped[] = "line {$line}: status {$status} is not a redirect — using 301";
                $status = 301;
            }

            // Last one wins, so a file listing a path twice does not fail the
            // upsert on its own duplicate.
            $rows[$from] = ['from' => $from, 'to' => $to, 'status' => $status];
        }

        fclose($handle);

        $existing = Redirect::whereIn('from', array_keys($rows))->pluck('from')->all();
        $updates = count(array_intersect(array_keys($rows), $existing));
        $inserts = count($rows) - $updates;

        foreach ($skipped as $note) {
            $this->components->warn($note);
        }

        foreach ($this->shadowed(array_keys($rows)) as $note) {
            $this->components->warn($note);
        }

        if ($this->option('dry-run')) {
            $this->components->info(
                "Dry run — {$inserts} would be added, {$updates} updated, ".count($skipped).' skipped.'
            );

            return self::SUCCESS;
        }

        // `hits` is deliberately absent from the update columns: re-importing
        // a mapping file corrects the destination without discarding what the
        // rule has been doing.
        foreach (array_chunk($rows, 500) as $chunk) {
            Redirect::upsert($chunk, ['from'], ['to', 'status']);
        }

        $this->components->info(
            "{$inserts} added, {$updates} updated, ".count($skipped).' skipped. '.
            DB::table('redirects')->count().' rules in total.'
        );

        return self::SUCCESS;
    }

    /**
     * The rules that will never fire, because live content already answers
     * that path.
     *
     * `RedirectResolver` hangs off the 404, so a rule for a path the site
     * still serves is dead — which is right, and is silent. Usually that is
     * harmless: a rule for a category that still exists is simply redundant.
     *
     * **One case is not harmless, and it is the common one.** `/{category}`
     * is constrained `.*` and `/{category}/{id}/{slug}` takes any numeric
     * middle segment, so a WordPress-style dated permalink —
     * `/2019/05/old-story` — matches `article.show` with article id 5. If
     * article 5 exists, `ArticleController` canonicalises and the reader is
     * 301'd to a story that has nothing to do with the one they asked for.
     * The rule sits at zero hits and nothing anywhere says why.
     *
     * That collision is a property of this site's URL scheme rather than
     * something a redirect table can fix, so the answer is to say so at
     * import time, while somebody still has the mapping file open.
     *
     * Two batch queries, whatever the size of the file.
     */
    private function shadowed(array $froms): array
    {
        $articleIds = [];
        $categoryPaths = [];
        $byArticle = [];
        $byCategory = [];

        foreach ($froms as $from) {
            // A `from` may carry a query string; only the path is routed.
            $path = '/'.strtok($from, '?');

            try {
                $route = Route::getRoutes()->match(Request::create($path, 'GET'));
            } catch (Throwable) {
                continue;                       // nothing matches: the rule will fire
            }

            if ($route->getName() === 'article.show') {
                $id = (int) $route->parameter('article');
                $articleIds[] = $id;
                $byArticle[$id][] = $from;
            } elseif ($route->getName() === 'category.show') {
                $categoryPath = (string) $route->parameter('category');
                $categoryPaths[] = $categoryPath;
                $byCategory[$categoryPath][] = $from;
            }
        }

        $notes = [];

        // Existence rather than visibility: a draft article 404s today, so the
        // rule works — right up until somebody publishes it.
        foreach (Article::whereIn('id', array_unique($articleIds))->pluck('id') as $id) {
            foreach ($byArticle[$id] ?? [] as $from) {
                $notes[] = "`{$from}` will never fire — it is routed to article {$id}, which exists";
            }
        }

        foreach (Category::whereIn('path', array_unique($categoryPaths))->pluck('path') as $path) {
            foreach ($byCategory[$path] ?? [] as $from) {
                $notes[] = "`{$from}` will never fire — the category `{$path}` still exists";
            }
        }

        return $notes;
    }

    /** The one stored form: no leading or trailing slash, no surrounding space. */
    private function normalise(string $value): string
    {
        return trim(trim($value), '/');
    }
}
