<?php

namespace Database\Factories;

use App\Enums\ArticleStatus;
use App\Enums\ArticleType;
use App\Models\Article;
use App\Models\Category;
use App\Models\User;
use Database\Seeders\Support\BanglaContent;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<Article>
 */
class ArticleFactory extends Factory
{
    public function definition(): array
    {
        $publishedAt = fake()->dateTimeBetween('-45 days', 'now');

        return [
            'category_id' => Category::factory(),
            'author_id' => User::factory()->reporter(),
            'title' => BanglaContent::headline(),
            'slug' => null,          // generated by the model
            'excerpt' => BanglaContent::excerpt(),
            'body' => BanglaContent::body(),
            'type' => ArticleType::News,
            'status' => ArticleStatus::Published,
            'published_at' => $publishedAt,
            'dateline' => BanglaContent::dateline(),
            'locale' => 'bn',

            // Long tail: most stories get modest traffic, a few go big. A flat
            // random range would make the most-read widget meaningless.
            'views' => (int) round(fake()->numberBetween(20, 400) ** 1.35),
            'image' => 'seed/'.fake()->numberBetween(1, 24).'.jpg',
            'image_caption' => BanglaContent::sentence(8),
            'image_credit' => 'ছবি: সংগৃহীত',
        ];
    }

    public function inCategory(Category $category): static
    {
        // Headline pools are keyed by top-level section, so a leaf category
        // uses its parent's slug. Only read the relation if it is already
        // loaded — lazy loading is disabled outside production.
        $pool = $category->relationLoaded('parent') && $category->parent
            ? $category->parent->slug
            : $category->slug;

        return $this->state(fn () => [
            'category_id' => $category->id,
            'title' => BanglaContent::headline($pool),
        ]);
    }

    public function draft(): static
    {
        return $this->state(fn () => [
            'status' => ArticleStatus::Draft,
            'published_at' => null,
        ]);
    }

    public function breaking(): static
    {
        return $this->state(fn () => [
            'is_breaking' => true,
            'breaking_until' => now()->addHours(6),
            'published_at' => now()->subMinutes(fake()->numberBetween(5, 180)),
        ]);
    }

    public function lead(): static
    {
        return $this->state(fn () => ['is_lead' => true, 'is_featured' => true]);
    }

    public function video(): static
    {
        return $this->state(fn () => [
            'type' => ArticleType::Video,
            'video_url' => 'https://www.youtube.com/watch?v='.fake()->regexify('[A-Za-z0-9_-]{11}'),
            'video_duration' => fake()->numberBetween(45, 900),
        ]);
    }

    public function opinion(): static
    {
        return $this->state(fn () => [
            'type' => ArticleType::Opinion,
            'title' => BanglaContent::headline('opinion'),
        ]);
    }

    public function premium(): static
    {
        return $this->state(fn () => ['is_premium' => true]);
    }
}
