<?php

namespace Database\Factories;

use App\Models\Gallery;
use App\Models\User;
use Database\Seeders\Support\BanglaContent;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<Gallery>
 */
class GalleryFactory extends Factory
{
    public function definition(): array
    {
        return [
            'user_id' => User::factory()->editor(),
            'title' => BanglaContent::headline(),
            'slug' => null,          // generated by the model
            'description' => BanglaContent::excerpt(),
            'status' => 'published',
            'published_at' => now()->subDay(),
        ];
    }

    public function draft(): static
    {
        return $this->state(fn () => ['status' => 'draft', 'published_at' => null]);
    }
}
