<?php

namespace Database\Factories;

use App\Models\Tag;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<Tag>
 */
class TagFactory extends Factory
{
    public function definition(): array
    {
        return [
            // Bangla by default: the slug rules that matter here (combining
            // marks surviving `Str::slug`) only bite on Bangla input, so a
            // Latin default would exercise the wrong path.
            'name' => fake()->unique()->randomElement([
                'ক্রিকেট', 'নির্বাচন', 'জলবায়ু', 'অর্থনীতি', 'শিক্ষা',
                'স্বাস্থ্য', 'প্রযুক্তি', 'রাজনীতি', 'চলচ্চিত্র', 'কৃষি',
            ]).'-'.fake()->unique()->numberBetween(1, 100000),
            'slug' => null,          // generated by the model
        ];
    }
}
